import { Html, Head, Main, NextScript } from 'next/document'

export default function Document() {
  return (
    <Html lang="en">
      <Head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" type="image/x-icon" sizes="16x16" />
        <title>Matrix Freight Calculator</title>
      </Head>
      <body className="__variable_1e4310 __variable_c3aa02 antialiased">
        <Main />
        <NextScript />
      </body>
    </Html>
  )
}